import './reset.css'
import './fontWeb.css'
import StyledComponentsTheme from '@/lib/registry'

export const metadata = {
    title: 'Maquinas de Pesca',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" >
            <head>
                <link
                    href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap"
                    rel="stylesheet"
                />
                <body
                    suppressHydrationWarning={true}
                >
                    <StyledComponentsTheme>{children}</StyledComponentsTheme>
                </body>
            </head>
        </html>
    )
}
